[package]
name = "ash-rtx-renderer"
version = "0.1.0"
edition = "2021"
authors = ["Stephan Seitz <stephan.seitz@fau.de>"]
license = "MIT"
readme = "README.md"
keywords = ["vulkan", "ash", "RTX"]
categories = ["graphics"]
repository = "https://github.com/theHamsta/highlight-assertions"


[dependencies]
once_cell = "1.8"
anyhow = "1.0"
clap = { version = "3.0.5", features = ["derive"] }
ash = { version = "0.35.0", default-features = false, features = ["linked"]}
ash-window = { version = "0.9"}
raw-window-handle = "0.4"
winit = "0.26.1"
ply-rs = "0.1.3"
log = "0.4.14"
pretty_env_logger = "0.4.0"
thiserror = "1.0.30"

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
raw-window-metal = "0.2"

#[dev-dependencies]
#ash = { path = "../ash", version = "0.35", default-features = false, }
#libloading = "0.7.1"
#regex = "1.5"
#serde = { version = "1.0", features = ["derive"] }
#serde_json = "1.0"
